export const LOGIN_DETAILS = "LOGIN_DETAILS";
export const LOGIN_DETAILS_SUCCESS = "LOGIN_DETAILS_SUCCESS";
export const LOGIN_DETAILS_FAILED = "LOGIN_DETAILS_FAILED";

export const LOG_OUT = "LOG_OUT";

export const ONBOARDING_DETAILS = "ONBOARDING_DETAILS";
export const ONBOARDING_DETAILS_SUCCESS = "ONBOARDING_DETAILS_SUCCESS";
export const ONBOARDING_DETAILS_FAILED = "ONBOARDING_DETAILS_FAILED";

export const CLEAR_ONBOARDING = "CLEAR_ONBOARDING";

export const CHECK_PROFILE_DETAILS = "CHECK_PROFILE_DETAILS";
export const CHECK_PROFILE_DETAILS_SUCCESS = "CHECK_PROFILE_DETAILS_SUCCESS";
export const CHECK_PROFILE_DETAILS_FAILED = "CHECK_PROFILE_DETAILS_FAILED";

export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const RESET_PASSWORD_DETAILS = "RESET_PASSWORD_DETAILS";
export const RESET_PASSWORD_DETAILS_SUCCESS = "RESET_PASSWORD_DETAILS_SUCCESS";
export const RESET_PASSWORD_DETAILS_FAILED = "RESET_PASSWORD_DETAILS_FAILED";

export const RESET_USER_EMAIL = "RESET_USER_EMAIL";

export const CLEAR_RESET_PASSWORD = "CLEAR_RESET_PASSWORD";
export const CLEAR_RESET_USER_EMAIL = "CLEAR_RESET_USER_EMAIL";

export const FORGOT_PASSWORD_DETAILS = "FORGOT_PASSWORD_DETAILS";
export const FORGOT_PASSWORD_DETAILS_SUCCESS =
  "FORGOT_PASSWORD_DETAILS_SUCCESS";
export const FORGOT_PASSWORD_DETAILS_FAILED = "FORGOT_PASSWORD_DETAILS_FAILED";

export const CLEAR_FORGOT_PASSWORD = "CLEAR_FORGOT_PASSWORD";

export const PUBLICATION_DETAILS = "PUBLICATION_DETAILS";
export const PUBLICATION_DETAILS_SUCCESS = "PUBLICATION_DETAILS_SUCCESS";
export const PUBLICATION_DETAILS_FAILED = "PUBLICATION_DETAILS_FAILED";

export const VERIFY_ACCOUNT_DETAILS = "VERIFY_ACCOUNT_DETAILS";
export const VERIFY_ACCOUNT_DETAILS_SUCCESS = "VERIFY_ACCOUNT_DETAILS_SUCCESS";
export const VERIFY_ACCOUNT_DETAILS_FAILED = "VERIFY_ACCOUNT_DETAILS_FAILED";

export const CLEAR_VERIFY_ACCOUNT = "CLEAR_VERIFY_ACCOUNT";

export const GRANTS_DETAILS = "GRANTS_DETAILS";
export const GRANTS_DETAILS_SUCCESS = "GRANTS_DETAILS_SUCCESS";
export const GRANTS_DETAILS_FAILED = "GRANTS_DETAILS_FAILED";

export const FUNDING_DETAILS = "FUNDING_DETAILS";
export const FUNDING_DETAILS_SUCCESS = "FUNDING_DETAILS_SUCCESS";
export const FUNDING_DETAILS_FAILED = "FUNDING_DETAILS_FAILED";

export const RECOMMENDATION_DETAILS = "RECOMMENDATION_DETAILS";
export const RECOMMENDATION_DETAILS_SUCCESS = "RECOMMENDATION_DETAILS_SUCCESS";
export const RECOMMENDATION_DETAILS_FAILED = "RECOMMENDATION_DETAILS_FAILED";
export const PERSONALIZED_RECOMMENDATION_DETAILS_SUCCESS =
  "PERSONALIZED_RECOMMENDATION_DETAILS_SUCCESS";

export const CLEAR_RECOMMENDATION = "CLEAR_RECOMMENDATION";

export const GET_USERS_DETAILS = "GET_USERS_DETAILS";
export const GET_USERS_DETAILS_SUCCESS = "GET_USERS_DETAILS_SUCCESS";
export const GET_USERS_DETAILS_FAILED = "GET_USERS_DETAILS_FAILED";

export const PREVIEW_PROFILE_DETAILS = "PREVIEW_PROFILE_DETAILS";
export const PREVIEW_PROFILE_DETAILS_SUCCESS =
  "PREVIEW_PROFILE_DETAILS_SUCCESS";
export const PREVIEW_PROFILE_DETAILS_FAILED = "PREVIEW_PROFILE_DETAILS_FAILED";

export const PREVIEW_PUBLICATION_DETAILS = "PREVIEW_PUBLICATION_DETAILS";
export const PREVIEW_PUBLICATION_DETAILS_SUCCESS =
  "PREVIEW_PUBLICATION_DETAILS_SUCCESS";
export const PREVIEW_PUBLICATION_DETAILS_FAILED =
  "PREVIEW_PUBLICATION_DETAILS_FAILED";

export const CLEAR_PREVIEW_PROFILE = "CLEAR_PREVIEW_PROFILE";
export const CLEAR_PREVIEW_PUBLICATIONS = "CLEAR_PREVIEW_PUBLICATIONS";

export const CONNECTION_DETAILS = "CONNECTION_DETAILS";
export const CONNECTION_DETAILS_SUCCESS = "CONNECTION_DETAILS_SUCCESS";
export const CONNECTION_DETAILS_FAILED = "CONNECTION_DETAILS_FAILED";

export const NOTIFICATION_DETAILS = "NOTIFICATION_DETAILS";
export const NOTIFICATION_DETAILS_SUCCESS = "NOTIFICATION_DETAILS_SUCCESS";
export const NOTIFICATION_DETAILS_FAILED = "NOTIFICATION_DETAILS_FAILED";

export const CONFIRMATION_DETAILS = "CONFIRMATION_DETAILS";
export const CONFIRMATION_DETAILS_SUCCESS = "CONFIRMATION_DETAILS_SUCCESS";
export const CONFIRMATION_DETAILS_FAILED = "CONFIRMATION_DETAILS_FAILED";

export const BTN_ACCEPT_OR_REJECT = "BTN_ACCEPT_OR_REJECT";
export const CLEAR_BTN_ACCEPT_OR_REJECT = "CLEAR_BTN_ACCEPT_OR_REJECT";

export const PREVIEW_CONFIRMATION_DETAILS = "PREVIEW_CONFIRMATION_DETAILS";
export const PREVIEW_CONFIRMATION_DETAILS_SUCCESS =
  "PREVIEW_CONFIRMATION_DETAILS_SUCCESS";
export const PREVIEW_CONFIRMATION_DETAILS_FAILED =
  "PREVIEW_CONFIRMATION_DETAILS_FAILED";

export const GRANTS_SAVE_OR_UPDATE_DETAILS = "GRANTS_SAVE_OR_UPDATE_DETAILS";
export const GRANTS_SAVE_OR_UPDATE_DETAILS_SUCCESS =
  "GRANTS_SAVE_OR_UPDATE_DETAILS_SUCCESS";
export const GRANTS_SAVE_OR_UPDATE_DETAILS_FAILED =
  "GRANTS_SAVE_OR_UPDATE_DETAILS_FAILED";

export const FILE_UPLOAD_DETAILS = "FILE_UPLOAD_DETAILS";
export const FILE_UPLOAD_DETAILS_SUCCESS = "FILE_UPLOAD_DETAILS_SUCCESS";
export const FILE_UPLOAD_DETAILS_FAILED = "FILE_UPLOAD_DETAILS_FAILED";

export const CLEAR_FILE_UPLOAD = "CLEAR_FILE_UPLOAD";

export const MESSAGE_DEATAILS = "MESSAGE_DEATAILS";
export const MESSAGE_DEATAILS_SUCCESS = "MESSAGE_DEATAILS_SUCCESS";
export const MESSAGE_DEATAILS_FAILED = "MESSAGE_DEATAILS_FAILED";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ACTIVATE_OR_DEACTIVATE_DETAILS = "ACTIVATE_OR_DEACTIVATE_DETAILS";
export const ACTIVATE_OR_DEACTIVATE_DETAILS_SUCCESS =
  "ACTIVATE_OR_DEACTIVATE_DETAILS_SUCCESS";
export const ACTIVATE_OR_DEACTIVATE_DETAILS_FAILED =
  "ACTIVATE_OR_DEACTIVATE_DETAILS_FAILED";

export const CLEAR_ACTIVATION = "CLEAR_ACTIVATION";

export const USER_ARRAY = "USER_ARRAY";

export const RATING_DETAILS = "RATING_DETAILS";
export const RATING_DETAILS_SUCCESS = "RATING_DETAILS_SUCCESS";
export const RATING_DETAILS_FAILED = "RATING_DETAILS_FAILED";

export const DELETE_OR_VERIFY_USER_DETAILS = "DELETE_OR_VERIFY_USER_DETAILS";
export const DELETE_OR_VERIFY_USER_DETAILS_SUCCESS =
  "DELETE_OR_VERIFY_USER_DETAILS_SUCCESS";
export const DELETE_OR_VERIFY_USER_DETAILS_FAILED =
  "DELETE_OR_VERIFY_USER_DETAILS_FAILED";

export const CLEAR_DELETE_OR_VERIFY_USER = "CLEAR_DELETE_OR_VERIFY_USER";

export const PREVIEW_USER_RATING_DEATILS = "PREVIEW_USER_RATING_DEATILS";
export const PREVIEW_USER_RATING_DEATILS_SUCCESS =
  "PREVIEW_USER_RATING_DEATILS_SUCCESS";
export const PREVIEW_USER_RATING_DEATILS_FAILED =
  "PREVIEW_USER_RATING_DEATILS_FAILED";

export const CLEAR_PREVIEW_USER_RATING = "CLEAR_PREVIEW_USER_RATING";

export const PREVIEW_USER_FUNDING_DEATILS = "PREVIEW_USER_FUNDING_DEATILS";
export const PREVIEW_USER_FUNDING_DEATILS_SUCCESS =
  "PREVIEW_USER_FUNDING_DEATILS_SUCCESS";
export const PREVIEW_USER_FUNDING_DEATILS_FAILED =
  "PREVIEW_USER_FUNDING_DEATILS_FAILED";

export const CLEAR_PREVIEW_USER_FUNDING = "CLEAR_PREVIEW_USER_FUNDING";

export const REMAKE_CONNECTION = "REMAKE_CONNECTION";

export const DISCONNECT_DETAILS = "DISCONNECT_DETAILS";
export const DISCONNECT_DETAILS_SUCCESS = "DISCONNECT_DETAILS_SUCCESS";
export const DISCONNECT_DETAILS_FAILED = "DISCONNECT_DETAILS_FAILED";

export const CTEATE_COLLABORATOR_DETAILS = "CTEATE_COLLABORATOR_DETAILS";
export const CTEATE_COLLABORATOR_DETAILS_SUCCESS =
  "CTEATE_COLLABORATOR_DETAILS_SUCCESS";
export const CTEATE_COLLABORATOR_DETAILS_FAILED =
  "CTEATE_COLLABORATOR_DETAILS_FAILED";

export const GET_COLLABORATORS_DETAILS = "GET_COLLABORATORS_DETAILS";
export const GET_COLLABORATORS_DETAILS_SUCCESS =
  "GET_COLLABORATORS_DETAILS_SUCCESS";
export const GET_COLLABORATORS_DETAILS_FAILED =
  "GET_COLLABORATORS_DETAILS_FAILED";

export const GET_PREVIEW_COLLABORATORS_DETAILS =
  "GET_PREVIEW_COLLABORATORS_DETAILS";
export const GET_PREVIEW_COLLABORATORS_DETAILS_SUCCESS =
  "GET_PREVIEW_COLLABORATORS_DETAILS_SUCCESS";
export const GET_PREVIEW_COLLABORATORS_DETAILS_FAILED =
  "GET_PREVIEW_COLLABORATORS_DETAILS_FAILED";

export const SHARE_GRANTS_DETAILS = "SHARE_GRANTS_DETAILS";
export const SHARE_GRANTS_DETAILS_SUCCESS = "SHARE_GRANTS_DETAILS_SUCCESS";
export const SHARE_GRANTS_DETAILS_FAILED = "SHARE_GRANTS_DETAILS_FAILED";

export const UPCOMINGS_DETAILS = "UPCOMINGS_DETAILS";
export const UPCOMINGS_DETAILS_SUCCESS = "UPCOMINGS_DETAILS_SUCCESS";
export const UPCOMINGS_DETAILS_FAILED = "UPCOMINGS_DETAILS_FAILED";
