# Define the evaluation criteria weights
weights = {
    'years_experience': 2.16/5,
    'position': 1.45/5,
    'h_index': 4.99/5,
    'publications': 4.06/5,
    'coauthors': 2.89/5,
    'citations': 4.93/5,
    'industry_collaborations': 2.80/5,
    'funding_grants': 3.94/5,
    'undergraduate_supervisions': 1.55/5,
    'msc_supervisions': 1.59/5,
    'phd_supervisions': 1.60/5,
    'chair_conferences': 2.82/5,
    'editor_journals': 4.00/5,
    'reviewer_conferences': 1.95/5,
    'reviewer_journals': 2.64/5
}

n_weights = ['undergraduate_supervisions', 'msc_supervisions', 'phd_supervisions', 'chair_conferences',
                                'editor_journals', 'reviewer_conferences', 'reviewer_journals']
m_weights = ['years_experience', 'position', 'h_index', 'publications',
                         'coauthors', 'citations', 'industry_collaborations', 'funding_grants']

position_values = {
    'Undergraduate Student': 1,
    "Master's Student": 2,
    'PhD Student': 3,
    'Postdoctoral Researcher': 4,
    'Assistant Professor': 5,
    'Associate Professor': 6,
    'Professor': 7,
    'Department Chair': 8,
    'Dean': 9,
    'Provost': 10
}

categories = {
        'IEEE': ['IEEE'],
        'ICAC': ['ICAC', 'International Conference on Autonomic Computing'],
        'ACM': ['ACM'],
        'ICIIS' :['ICIIS'],
        'Elsevier': ['Elsevier'],
        'Springer': ['Springer'],
        'Nature': ['Nature'],
        'Science': ['Science'],
        'Journal of the American Chemical Society': ['Journal of the American Chemical Society', 'JACS'],
        'Cell': ['Cell'],
        'Physical Review Letters': ['Physical Review Letters', 'PRL'],
        'The Lancet': ['The Lancet'],
        'New England Journal of Medicine': ['New England Journal of Medicine', 'NEJM'],
        'Cell Stem Cell': ['Cell Stem Cell'],
        'Advanced Materials': ['Advanced Materials'],
        'Bioinformatics': ['Bioinformatics'],
        'Journal of Biological Chemistry': ['Journal of Biological Chemistry', 'JBC'],
        'Information and Computation': ['Information and Computation'],
        'International Journal of Computer Vision': ['International Journal of Computer Vision', 'IJCV'],
        'Machine Learning': ['Machine Learning'],
        'Journal of Machine Learning Research': ['Journal of Machine Learning Research', 'JMLR'],
        'Journal of the Royal Society Interface': ['Journal of the Royal Society Interface'],
        'Biochimica et Biophysica Acta': ['Biochimica et Biophysica Acta', 'BBA'],
        'Angewandte Chemie International Edition': ['Angewandte Chemie International Edition', 'Angew. Chem. Int. Ed.'],
        'Journal of Physical Chemistry': ['Journal of Physical Chemistry', 'JPC'],
        'IEEE Transactions on Pattern Analysis and Machine Intelligence': ['IEEE Transactions on Pattern Analysis and Machine Intelligence', 'TPAMI'],
        'Journal of the American Medical Association': ['Journal of the American Medical Association', 'JAMA'],
        'Journal of Neuroscience': ['Journal of Neuroscience'],
        'Proceedings of the National Academy of Sciences': ['Proceedings of the National Academy of Sciences', 'PNAS'],
        'IEEE Transactions on Information Theory': ['IEEE Transactions on Information Theory'],
        'Journal of Materials Chemistry': ['Journal of Materials Chemistry'],
        'Journal of Economic Theory': ['Journal of Economic Theory'],
        'Computer Vision and Image Understanding': ['Computer Vision and Image Understanding', 'CVIU'],
        'Journal of Statistical Software': ['Journal of Statistical Software', 'JSS'],
        'Journal of High Energy Physics': ['Journal of High Energy Physics', 'JHEP'],
        'International Journal of Robotics Research': ['International Journal of Robotics Research', 'IJRR'],
        'Journal of Geophysical Research': ['Journal of Geophysical Research', 'JGR'],
        'IEEE Transactions on Visualization and Computer Graphics': ['IEEE Transactions on Visualization and Computer Graphics', 'TVCG'],
        'Journal of Physical Chemistry Letters': ['Journal of Physical Chemistry Letters', 'JPCL'],
        'Frontiers in Neuroinformatics': ['Frontiers in Neuroinformatics'],
        'Journal of Applied Physics': ['Journal of Applied Physics'],
        'Journal of Mathematical Physics': ['Journal of Mathematical Physics'],
        'Computer Methods in Applied Mechanics and Engineering': ['Computer Methods in Applied Mechanics and Engineering'],
        'Journal of Chemical Theory and Computation': ['Journal of Chemical Theory and Computation', 'JCTC'],
        'IEEE Transactions on Automatic Control': ['IEEE Transactions on Automatic Control'],
        'Journal of Financial Economics': ['Journal of Financial Economics'],
        'Journal of Consumer Research': ['Journal of Consumer Research'],
        'Journal of Physical Oceanography': ['Journal of Physical Oceanography'],
        'IEEE Journal of Selected Topics in Signal Processing': ['IEEE Journal of Selected Topics in Signal Processing'],
        'Journal of Human Resources': ['Journal of Human Resources'],
        'Science Robotics': ['Science Robotics'],
        'Physical Review X': ['Physical Review X', 'PRX'],
        'The Astrophysical Journal': ['The Astrophysical Journal', 'ApJ'],
        'Journal of Clinical Oncology': ['Journal of Clinical Oncology', 'JCO'],
        'Journal of Materials Science': ['Journal of Materials Science'],
        'Journal of Experimental Psychology': ['Journal of Experimental Psychology'],
        'IEEE Transactions on Robotics': ['IEEE Transactions on Robotics'],
        'Journal of Applied Ecology': ['Journal of Applied Ecology'],
        'Journal of Physical Chemistry C': ['Journal of Physical Chemistry C', 'JPCC'],
        'IEEE Transactions on Wireless Communications': ['IEEE Transactions on Wireless Communications'],
        'Journal of Environmental Management': ['Journal of Environmental Management'],
        'Journal of Neuroscience Methods': ['Journal of Neuroscience Methods'],
        'Journal of the American Society of Nephrology': ['Journal of the American Society of Nephrology', 'JASN'],
        'Journal of Atmospheric and Solar-Terrestrial Physics': ['Journal of Atmospheric and Solar-Terrestrial Physics'],
        'Journal of Fluid Mechanics': ['Journal of Fluid Mechanics', 'JFM'],
        'Journal of Economic Geography': ['Journal of Economic Geography'],
        'Journal of Physical Chemistry B': ['Journal of Physical Chemistry B', 'JPCC'],
        'IEEE Transactions on Neural Networks and Learning Systems': ['IEEE Transactions on Neural Networks and Learning Systems'],
        'Journal of the American College of Cardiology': ['Journal of the American College of Cardiology', 'JACC'],
        'Journal of Virology': ['Journal of Virology'],
        'Journal of Applied Physiology': ['Journal of Applied Physiology'],
        'Journal of Climate': ['Journal of Climate'],
        'Journal of Financial and Quantitative Analysis': ['Journal of Financial and Quantitative Analysis'],
        'Journal of Operations Management': ['Journal of Operations Management'],
        'Journal of the American Society for Mass Spectrometry': ['Journal of the American Society for Mass Spectrometry', 'JASMS'],
        'Journal of Environmental Economics and Management': ['Journal of Environmental Economics and Management'],
        'Journal of Machine Learning and Data Mining': ['Journal of Machine Learning and Data Mining'],
        'Journal of Development Economics': ['Journal of Development Economics'],
        'Journal of Physical Chemistry A': ['Journal of Physical Chemistry A', 'JPCC'],
        'IEEE Transactions on Cybernetics': ['IEEE Transactions on Cybernetics'],
        'Journal of Experimental Biology': ['Journal of Experimental Biology'],
        'Journal of the American Chemical Society Letters': ['Journal of the American Chemical Society Letters', 'JACS'],
        'Journal of Power Sources': ['Journal of Power Sources'],
        'Journal of Cleaner Production': ['Journal of Cleaner Production'],
        'Journal of Structural Biology': ['Journal of Structural Biology'],
        'Journal of Analytical Chemistry': ['Journal of Analytical Chemistry'],
        'Journal of Microelectromechanical Systems': ['Journal of Microelectromechanical Systems', 'JMEMS'],
        'Journal of the American Academy of Dermatology': ['Journal of the American Academy of Dermatology'],
        'Journal of Lightwave Technology': ['Journal of Lightwave Technology'],
        'Journal of Experimental Social Psychology': ['Journal of Experimental Social Psychology'],
        'Journal of Physical Chemistry Letters': ['Journal of Physical Chemistry Letters', 'JPCL'],
        'Journal of Analytical Atomic Spectrometry': ['Journal of Analytical Atomic Spectrometry', 'JAAS'],
        'Journal of Non-Crystalline Solids': ['Journal of Non-Crystalline Solids'],
        'Journal of Urban Economics': ['Journal of Urban Economics'],
        'Journal of Industrial Ecology': ['Journal of Industrial Ecology'],
        'Journal of Medicinal Chemistry': ['Journal of Medicinal Chemistry'],
        'Journal of Alloys and Compounds': ['Journal of Alloys and Compounds'],
        'Journal of Fluids Engineering': ['Journal of Fluids Engineering'],
        'Journal of Chemical Physics': ['Journal of Chemical Physics'],
        'Journal of Environmental Science and Technology': ['Journal of Environmental Science and Technology'],
        'Journal of the American Water Resources Association': ['Journal of the American Water Resources Association', 'JAWRA'],
        'Journal of Optics': ['Journal of Optics'],
        'Journal of the American Ceramic Society': ['Journal of the American Ceramic Society', 'JACS'],
        'Journal of Statistical Mechanics: Theory and Experiment': ['Journal of Statistical Mechanics: Theory and Experiment', 'JSTAT'],
        'Journal of Membrane Science': ['Journal of Membrane Science'],
        'Journal of Biomechanics': ['Journal of Biomechanics'],
        'Journal of Clinical Investigation': ['Journal of Clinical Investigation', 'JCI'],
        'Journal of Colloid and Interface Science': ['Journal of Colloid and Interface Science'],
        'Journal of Structural Geology': ['Journal of Structural Geology'],
        'Journal of Physical Chemistry C': ['Journal of Physical Chemistry C', 'JPCC'],
        'Journal of Organometallic Chemistry': ['Journal of Organometallic Chemistry'],
        'Journal of the American Society of Mechanical Engineers': ['Journal of the American Society of Mechanical Engineers', 'JASME'],
        'Journal of the Electrochemical Society': ['Journal of the Electrochemical Society', 'JES'],
        'Journal of Chemical Information and Modeling': ['Journal of Chemical Information and Modeling'],
        'Journal of Applied Electrochemistry': ['Journal of Applied Electrochemistry'],
        'Journal of Control Theory and Applications': ['Journal of Control Theory and Applications'],
        'Journal of Neurophysiology': ['Journal of Neurophysiology'],
        'Journal of Environmental Psychology': ['Journal of Environmental Psychology'],
        'Journal of Thermal Analysis and Calorimetry': ['Journal of Thermal Analysis and Calorimetry'],
        'Journal of Computational Chemistry': ['Journal of Computational Chemistry'],
        'Journal of Geology': ['Journal of Geology'],
        'Journal of the American Society for Mass Spectrometry Letters': ['Journal of the American Society for Mass Spectrometry Letters', 'JASMS'],
        'Journal of the Electrochemical Society Letters': ['Journal of the Electrochemical Society Letters', 'JES'],
        'Journal of the Royal Statistical Society: Series B': ['Journal of the Royal Statistical Society: Series B', 'JRSSB'],
        'Journal of Environmental Sciences': ['Journal of Environmental Sciences'],
        'Journal of the Royal Society of Medicine': ['Journal of the Royal Society of Medicine', 'JRSM'],
        'Journal of Power Sources and Energy Conversion': ['Journal of Power Sources and Energy Conversion'],
        'Journal of the European Economic Association': ['Journal of the European Economic Association'],
        'Journal of Hazardous Materials': ['Journal of Hazardous Materials'],
        'Journal of Medical Internet Research': ['Journal of Medical Internet Research', 'JMIR'],
        'Journal of Natural Products': ['Journal of Natural Products'],
        'Journal of Physical Chemistry Research': ['Journal of Physical Chemistry Research', 'JPCR'],
        'Journal of Analytical and Applied Pyrolysis': ['Journal of Analytical and Applied Pyrolysis'],
        'Journal of Physical Oceanography and Climate': ['Journal of Physical Oceanography and Climate'],
        'Journal of Materials Research': ['Journal of Materials Research'],
        'Journal of Environmental Monitoring': ['Journal of Environmental Monitoring'],
        'Journal of Materials Chemistry A': ['Journal of Materials Chemistry A'],
        'Journal of Physical Organic Chemistry': ['Journal of Physical Organic Chemistry'],
        'Journal of Atmospheric Sciences': ['Journal of Atmospheric Sciences'],
        'Journal of Physical and Chemical Reference Data': ['Journal of Physical and Chemical Reference Data', 'JPCRD'],
        'Journal of Astronomical Telescopes, Instruments, and Systems': ['Journal of Astronomical Telescopes, Instruments, and Systems', 'JATIS'],
        'Journal of Food Engineering': ['Journal of Food Engineering'],
        'Journal of Microbiology and Biotechnology': ['Journal of Microbiology and Biotechnology'],
        'Journal of Structural Engineering': ['Journal of Structural Engineering'],
        'Journal of Photochemistry and Photobiology A: Chemistry': ['Journal of Photochemistry and Photobiology A: Chemistry'],
        'Journal of Applied Electrochemistry and Materials Science': ['Journal of Applied Electrochemistry and Materials Science'],
        'Journal of Paleontology': ['Journal of Paleontology'],
        'Journal of Atmospheric Chemistry': ['Journal of Atmospheric Chemistry'],
        'Journal of Solid State Chemistry': ['Journal of Solid State Chemistry'],
        'Journal of Dental Research': ['Journal of Dental Research'],
        'Journal of Mathematical Analysis and Applications': ['Journal of Mathematical Analysis and Applications'],
        'Journal of Physical Chemistry D': ['Journal of Physical Chemistry D', 'JPCC'],
        'Journal of Applied Mathematics and Physics': ['Journal of Applied Mathematics and Physics'],
        'Journal of Astronomical Telescopes and Instrumentation': ['Journal of Astronomical Telescopes and Instrumentation'],
        'Journal of the American Society for Horticultural Science': ['Journal of the American Society for Horticultural Science', 'JASHS'],
        'Journal of Molecular Biology': ['Journal of Molecular Biology'],
        'Journal of Materials Science: Materials in Electronics': ['Journal of Materials Science: Materials in Electronics'],
        'Journal of Biological Inorganic Chemistry': ['Journal of Biological Inorganic Chemistry', 'JBIC'],
        'Journal of Fluid Mechanics and Hydraulics': ['Journal of Fluid Mechanics and Hydraulics'],
        'Journal of Mechanical Science and Technology': ['Journal of Mechanical Science and Technology'],
        'Journal of Petroleum Science and Engineering': ['Journal of Petroleum Science and Engineering'],
        'Journal of Industrial and Engineering Chemistry': ['Journal of Industrial and Engineering Chemistry'],
        'Journal of Sedimentary Research': ['Journal of Sedimentary Research'],
        'Journal of Waterway, Port, Coastal, and Ocean Engineering': ['Journal of Waterway, Port, Coastal, and Ocean Engineering'],
        'Journal of Biomolecular NMR': ['Journal of Biomolecular NMR'],
        'Journal of Geophysical Research: Atmospheres': ['Journal of Geophysical Research: Atmospheres', 'JGRA'],
        'Journal of Experimental Botany': ['Journal of Experimental Botany'],
        'Journal of Materials Science: Materials in Medicine': ['Journal of Materials Science: Materials in Medicine'],
        'Journal of Coastal Research': ['Journal of Coastal Research'],
        'Journal of Electroanalytical Chemistry': ['Journal of Electroanalytical Chemistry'],
        'Journal of Applied Polymer Science': ['Journal of Applied Polymer Science'],
        'Journal of Physical Chemistry A': ['Journal of Physical Chemistry A', 'JPCC'],
        'Journal of Heat Transfer': ['Journal of Heat Transfer'],
        'Journal of Environmental Radioactivity': ['Journal of Environmental Radioactivity'],
        'Journal of Chemical Education': ['Journal of Chemical Education'],
        'Journal of Statistical Physics': ['Journal of Statistical Physics'],
        'Journal of Food Science': ['Journal of Food Science'],
        'Journal of Comparative Physiology B': ['Journal of Comparative Physiology B'],
        'Journal of Water Resources Planning and Management': ['Journal of Water Resources Planning and Management'],
        'Journal of Pharmacology and Experimental Therapeutics': ['Journal of Pharmacology and Experimental Therapeutics'],
        'Journal of Supercritical Fluids': ['Journal of Supercritical Fluids'],
        'Journal of the Mechanics and Physics of Solids': ['Journal of the Mechanics and Physics of Solids'],
        'Journal of Inorganic Biochemistry': ['Journal of Inorganic Biochemistry'],
        'Journal of Physical Chemistry Letters': ['Journal of Physical Chemistry Letters', 'JPCL'],
        'Journal of Synthetic Organic Chemistry, Japan': ['Journal of Synthetic Organic Chemistry, Japan'],
        'Journal of the Royal Society Interface Focus': ['Journal of the Royal Society Interface Focus'],
        'Journal of Physical Chemistry E': ['Journal of Physical Chemistry E', 'JPCC'],
        'Journal of Applied Remote Sensing': ['Journal of Applied Remote Sensing'],
        'Journal of Nanoscience and Nanotechnology': ['Journal of Nanoscience and Nanotechnology'],
        'Journal of Agricultural and Food Chemistry': ['Journal of Agricultural and Food Chemistry'],
        'Journal of Atmospheric and Oceanic Technology': ['Journal of Atmospheric and Oceanic Technology'],
        'Journal of Cell Biology': ['Journal of Cell Biology'],
        'Journal of Statistical Planning and Inference': ['Journal of Statistical Planning and Inference'],
        'Journal of Computational Physics': ['Journal of Computational Physics'],
        'Journal of Cardiovascular Electrophysiology': ['Journal of Cardiovascular Electrophysiology'],
        'Journal of Membrane Biology': ['Journal of Membrane Biology'],
        'Journal of Coastal Research, Special Issue': ['Journal of Coastal Research, Special Issue'],
        'Journal of Separation Science': ['Journal of Separation Science'],
        'Journal of Economic Dynamics and Control': ['Journal of Economic Dynamics and Control'],
        'Journal of Physical Chemistry B': ['Journal of Physical Chemistry B', 'JPCC'],
        'Journal of Physics D: Applied Physics': ['Journal of Physics D: Applied Physics'],
        'Journal of the Optical Society of America B': ['Journal of the Optical Society of America B'],
        'Journal of Renewable and Sustainable Energy': ['Journal of Renewable and Sustainable Energy'],
        'Journal of Materials Science: Materials in Electronics': ['Journal of Materials Science: Materials in Electronics'],
        'Journal of Agricultural and Food Chemistry': ['Journal of Agricultural and Food Chemistry'],
        'Journal of Atmospheric and Oceanic Technology': ['Journal of Atmospheric and Oceanic Technology'],
        'Journal of Cell Biology': ['Journal of Cell Biology'],
        'Journal of Statistical Planning and Inference': ['Journal of Statistical Planning and Inference'],
        'Journal of Computational Physics': ['Journal of Computational Physics'],
        'Journal of Cardiovascular Electrophysiology': ['Journal of Cardiovascular Electrophysiology'],
        'Journal of Membrane Biology': ['Journal of Membrane Biology'],
        'Journal of Coastal Research, Special Issue': ['Journal of Coastal Research, Special Issue'],
        'Journal of Separation Science': ['Journal of Separation Science'],
        'Journal of Economic Dynamics and Control': ['Journal of Economic Dynamics and Control'],
        'Journal of Physical Chemistry B': ['Journal of Physical Chemistry B', 'JPCC'],
        'Journal of Physics D: Applied Physics': ['Journal of Physics D: Applied Physics'],
        'Journal of the Optical Society of America B': ['Journal of the Optical Society of America B'],
        'Journal of Renewable and Sustainable Energy': ['Journal of Renewable and Sustainable Energy'],
        'Journal of Materials Science: Materials in Electronics': ['Journal of Materials Science: Materials in Electronics'],
        'Journal of Agricultural and Food Chemistry': ['Journal of Agricultural and Food Chemistry'],
        'Journal of Atmospheric and Oceanic Technology': ['Journal of Atmospheric and Oceanic Technology'],
        'Journal of Cell Biology': ['Journal of Cell Biology'],
        'Journal of Statistical Planning and Inference': ['Journal of Statistical Planning and Inference'],
        'Journal of Computational Physics': ['Journal of Computational Physics'],
        'Journal of Cardiovascular Electrophysiology': ['Journal of Cardiovascular Electrophysiology'],
        'Journal of Membrane Biology': ['Journal of Membrane Biology'],
        'Journal of Coastal Research, Special Issue': ['Journal of Coastal Research, Special Issue'],
        'Journal of Separation Science': ['Journal of Separation Science'],
        'Journal of Economic Dynamics and Control': ['Journal of Economic Dynamics and Control'],
        'Journal of Physical Chemistry B': ['Journal of Physical Chemistry B', 'JPCC'],
        'Journal of Physics D: Applied Physics': ['Journal of Physics D: Applied Physics'],
        'Journal of the Optical Society of America B': ['Journal of the Optical Society of America B'],
        'Journal of Renewable and Sustainable Energy': ['Journal of Renewable and Sustainable Energy'],
        'Journal of Materials Science: Materials in Electronics': ['Journal of Materials Science: Materials in Electronics'],
        'Journal of Agricultural and Food Chemistry': ['Journal of Agricultural and Food Chemistry'],
        'Journal of Atmospheric and Oceanic Technology': ['Journal of Atmospheric and Oceanic Technology'],
        'Journal of Cell Biology': ['Journal of Cell Biology'],
        'Journal of Statistical Planning and Inference': ['Journal of Statistical Planning and Inference'],
        'Journal of Computational Physics': ['Journal of Computational Physics'],
        'Journal of Cardiovascular Electrophysiology': ['Journal of Cardiovascular Electrophysiology'],
        'Journal of Membrane Biology': ['Journal of Membrane Biology'],
        'Journal of Coastal Research, Special Issue': ['Journal of Coastal Research, Special Issue'],
        'Journal of Separation Science': ['Journal of Separation Science'],
        'Journal of Economic Dynamics and Control': ['Journal of Economic Dynamics and Control'],
        'Journal of Physical Chemistry B': ['Journal of Physical Chemistry B', 'JPCC'],
        'Journal of Physics D: Applied Physics': ['Journal of Physics D: Applied Physics'],
        'Journal of the Optical Society of America B': ['Journal of the Optical Society of America B'],
        'Journal of Renewable and Sustainable Energy': ['Journal of Renewable and Sustainable Energy'],
        'Journal of Materials Science: Materials in Electronics': ['Journal of Materials Science: Materials in Electronics'],
        'Journal of Agricultural and Food Chemistry': ['Journal of Agricultural and Food Chemistry'],
        'Journal of Atmospheric and Oceanic Technology': ['Journal of Atmospheric and Oceanic Technology'],
        'Journal of Cell Biology': ['Journal of Cell Biology'],
        'Journal of Statistical Planning and Inference': ['Journal of Statistical Planning and Inference'],
        'Journal of Computational Physics': ['Journal of Computational Physics'],
        'Journal of Cardiovascular Electrophysiology': ['Journal of Cardiovascular Electrophysiology'],
        'Journal of Membrane Biology': ['Journal of Membrane Biology'],
        'Journal of Coastal Research, Special Issue': ['Journal of Coastal Research, Special Issue'],
        'Journal of Separation Science': ['Journal of Separation Science'],
        'Journal of Economic Dynamics and Control': ['Journal of Economic Dynamics and Control'],
        'Journal of Physical Chemistry B': ['Journal of Physical Chemistry B', 'JPCC'],
        'Journal of Physics D: Applied Physics': ['Journal of Physics D: Applied Physics'],
        'Journal of the Optical Society of America B': ['Journal of the Optical Society of America B'],
        'Journal of Renewable and Sustainable Energy': ['Journal of Renewable and Sustainable Energy'],
        'Journal of Materials Science: Materials in Electronics': ['Journal of Materials Science: Materials in Electronics'],
        'Journal of Agricultural and Food Chemistry': ['Journal of Agricultural and Food Chemistry'],
        'Journal of Atmospheric and Oceanic Technology': ['Journal of Atmospheric and Oceanic Technology'],
        'Journal of Cell Biology': ['Journal of Cell Biology'],
        'Journal of Statistical Planning and Inference': ['Journal of Statistical Planning and Inference'],
        'Journal of Computational Physics': ['Journal of Computational Physics'],
        'Journal of Cardiovascular Electrophysiology': ['Journal of Cardiovascular Electrophysiology'],
        'Journal of Membrane Biology': ['Journal of Membrane Biology'],
        'Journal of Coastal Research, Special Issue': ['Journal of Coastal Research, Special Issue'],
        'Journal of Separation Science': ['Journal of Separation Science'],
        'Journal of Economic Dynamics and Control': ['Journal of Economic Dynamics and Control'],
        'Journal of Physical Chemistry B': ['Journal of Physical Chemistry B', 'JPCC'],
        'Journal of Physics D: Applied Physics': ['Journal of Physics D: Applied Physics'],
        'Journal of the Optical Society of America B': ['Journal of the Optical Society of America B'],
        'Journal of Renewable and Sustainable Energy': ['Journal of Renewable and Sustainable Energy'],
        'Journal of Materials Science: Materials in Electronics': ['Journal of Materials Science: Materials in Electronics'],
        'Journal of Agricultural and Food Chemistry': ['Journal of Agricultural and Food Chemistry'],
        'Journal of Atmospheric and Oceanic Technology': ['Journal of Atmospheric and Oceanic Technology'],
        'Journal of Cell Biology': ['Journal of Cell Biology'],
        'Journal of Statistical Planning and Inference': ['Journal of Statistical Planning and Inference'],
        'Journal of Computational Physics': ['Journal of Computational Physics'],
        'Journal of Cardiovascular Electrophysiology': ['Journal of Cardiovascular Electrophysiology'],
        'Journal of Membrane Biology': ['Journal of Membrane Biology'],
        'Journal of Coastal Research, Special Issue': ['Journal of Coastal Research, Special Issue'],
        'Journal of Separation Science': ['Journal of Separation Science'],
        'Journal of Economic Dynamics and Control': ['Journal of Economic Dynamics and Control'],
        'Journal of Physical Chemistry B': ['Journal of Physical Chemistry B', 'JPCC'],
        'Journal of Physics D: Applied Physics': ['Journal of Physics D: Applied Physics'],
        'Journal of the Optical Society of America B': ['Journal of the Optical Society of America B'],
        'Journal of Renewable and Sustainable Energy': ['Journal of Renewable and Sustainable Energy'],
        'Journal of Materials Science: Materials in Electronics': ['Journal of Materials Science: Materials in Electronics'],
        'Journal of Agricultural and Food Chemistry': ['Journal of Agricultural and Food Chemistry'],
        'Journal of Atmospheric and Oceanic Technology': ['Journal of Atmospheric and Oceanic Technology'],
        'Journal of Cell Biology': ['Journal of Cell Biology'],
        'Journal of Statistical Planning and Inference': ['Journal of Statistical Planning and Inference'],
        'Journal of Computational Physics': ['Journal of Computational Physics'],
        'Journal of Cardiovascular Electrophysiology': ['Journal of Cardiovascular Electrophysiology'],
        'Journal of Membrane Biology': ['Journal of Membrane Biology'],
        'Journal of Coastal Research, Special Issue': ['Journal of Coastal Research, Special Issue'],
        'Journal of Separation Science': ['Journal of Separation Science'],
        'Journal of Economic Dynamics and Control': ['Journal of Economic Dynamics and Control'],
        'Journal of Physical Chemistry B': ['Journal of Physical Chemistry B', 'JPCC'],
        'Journal of Physics D: Applied Physics': ['Journal of Physics D: Applied Physics'],
}